language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "iojs"

services:

before_script:
    - chmod ugo-r  ./test/data/test-no-perms.log
    - chmod ugo-w ./test/data/nowrite
    - chmod ugo-r ./test/data/noread

after_success:
    - npm run coveralls

sudo: false
