language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "iojs"

services:

before_script:
    - chmod -r ./test/data/test-no-perms.log
    - chmod -rw ./test/data.nowrite

after_success:
    - npm run coveralls

sudo: false
